--Usuario SQL
CREATE USER EXPEDIENTE IDENTIFIED BY "asd.456"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER EXPEDIENTE QUOTA UNLIMITED ON USERS;

-- otorgando privilegios
GRANT ALTER ANY TABLE TO EXPEDIENTE ;
GRANT ALTER DATABASE TO EXPEDIENTE ;
GRANT ALTER SESSION TO EXPEDIENTE ;
GRANT ALTER TABLESPACE TO EXPEDIENTE ;
GRANT ALTER USER TO EXPEDIENTE ;
GRANT COMMENT ANY TABLE TO EXPEDIENTE ;
GRANT CREATE ANY PROCEDURE TO EXPEDIENTE;
GRANT CREATE SEQUENCE TO EXPEDIENTE;
GRANT CREATE SESSION TO EXPEDIENTE ;
GRANT CREATE TABLE TO EXPEDIENTE ;
GRANT CREATE TABLESPACE TO EXPEDIENTE ;
GRANT CREATE TRIGGER TO EXPEDIENTE;
GRANT CREATE VIEW TO EXPEDIENTE ;
GRANT DELETE ANY TABLE TO EXPEDIENTE ;
GRANT DROP ANY TABLE TO EXPEDIENTE ;
GRANT DROP ANY TRIGGER TO EXPEDIENTE ;
GRANT DROP PROCEDURE TO EXPEDIENTE;
GRANT DROP PROFILE TO EXPEDIENTE ;
GRANT DROP TABLESPACE TO EXPEDIENTE ;
GRANT DROP USER TO EXPEDIENTE ;
GRANT INSERT ANY TABLE TO EXPEDIENTE ;
GRANT SELECT ANY TABLE TO EXPEDIENTE ;
GRANT UPDATE ANY TABLE TO EXPEDIENTE ;