------------------------- VISTAS ATENCION PRE HOSPITALARIA ------------------------
CREATE OR REPLACE VIEW vistaAPH
AS
SELECT 
 A.PLACA,
 CM.NOMBRE,
 APH.ID_ATENCION,
 E.ID_EXPEDIENTE,
 P.P_NOMBRE,
 P.P_APELLIDO
 PA
FROM AMBULANCIA A 
INNER JOIN CENTROMEDICO CM
  ON CM.ID_CENTROMEDICO=A.ID_CENTROMEDICO
INNER JOIN  ATENCIONPREHOSPITALARIA APH
  ON APH.ID_AMBULANCIA= A.ID_AMBULANCIA
INNER JOIN PARAMEDICO PA
  ON P.ID_PARAMEDICO=APH.ID_PARAMEDICO
INNER JOIN PERSONA P
  ON P.ID_PERSONA= PA.ID_PARAMEDICO
INNER JOIN EXPEDIENTE EX 
  ON EX.ID_PERSONA=P.ID_PERSONA;


----------------------- CONSULTAS

-- listarTodos /*Por centro*/
SELECT
  *
FROM vistaAPH

;

-- listarPorAmbulancia
SELECT
  *
FROM vistaAPH V
WHERE V.PLACA= 123;
;

-- listarPorcentroMedico
SELECT
  *
FROM vistaAPH V 
WHERE
   V.NOMBRE='MEDICAL CENTER'
;
-- listarPor PARAMEDICO
SELECT
  *
FROM vistaAPH V
WHERE
   V.ID_PARAMEDICO=321
;

--eliminar
DELETE FROM ATENCIONPREHOSPITALARIA
WHERE ID_ATENCION = 1;