------------------------- VISTA CIRUGIA ------------------------
CREATE OR REPLACE VIEW VistaCirugia
AS
SELECT
    C.*,
    TC.DESCRIPCION,
    H.ID_HOSPITALIZACION,
    H.*
FROM CONSULTAEXTERNA CE
INNER JOIN CONSULTORIO C
  ON C.ID_CONSULTORIO=CE.ID_CONSULTORIO.,
INNER JOIN EXPEDIENTE EX 
  ON EX.ID_EXPEDIENTE=CE.ID_EXPEDIENTE
INNER JOIN MEDICO M 
  ON M.ID_MEDICO=CE.ID_MEDICO
INNER JOIN PISO PI
  ON PI.ID_PISO=C.ID_PISO
INNER JOIN EDIFICIO E 
  ON E.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM 
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN PACIENTE PA 
  ON PA.ID_PACIENTE= EX,ID_PACIENTE
INNER JOIN PERSONA PE 
  ON PE.ID_PERSONA= PA.ID_PERSONA

;

----------------------- CONSULTAS

-- listarTodos /*Por centro*/
SELECT
  *
FROM VistaConsultaExterna
;

-- listarPorPaciente
SELECT
  *
FROM VistaConsultaExterna V
WHERE
  V.ID_EXPEDIENTE=123
;
-- listarPor MEDICO
SELECT
  *
FROM Vistacirugia V
WHERE
  V.ID_MEDICO = 1
;
-- listar Por MEDICO FECHA
SELECT
  *
FROM Vistacirugia V
WHERE
  V.ID_MEDICO = 1 AND V.FECHA_HORA= TO_DATE('27/02/18')
;

--LISTAR POR HOY
SELECT *
FROM Vistacirugia V
WHERE V.FECHA_HORA= SYSDATE;

--LISTAR POR CENTRO MEDICO
SELECT*
FROM Vistacirugia V
WHERE V.ID_CENTRO_MEDICO=1;

--LISTAR POR CENTRO MEDICO FECHA
SELECT*
FROM Vistacirugia V
WHERE V.ID_CENTRO_MEDICO=1 AND V.FECHA_HORA= TO_DATE ('27/02/18')
;

--eliminar
DELETE FROM CIRUGIA
WHERE ID_CIRUGIA = 1;