----------------------- CONSULTAS

-- listarTodos /*Por centro*/
SELECT
  *
FROM VistaConsultaExterna
;

-- listarPorPaciente
SELECT
  *
FROM VistaConsultaExterna V
WHERE
  V.ID_EXPEDIENTE=123
;


--LISTAR POR CENTRO MEDICO
SELECT*
FROM VistaConsultaExterna V 
WHERE V.ID_CENTRO_MEDICO=1 OR V.NOMBRE LIKE 'HOSPITAL ESCUELA%';

--LISTAR POR HOY
SELECT *
FROM VistaConsultaExterna V 
WHERE V.FECHA_HORA= SYSDATE;

-- listarPor MEDICO
SELECT
  *
FROM VistaConsultaExterna V
WHERE
  V.ID_MEDICO = 1
;
-- listar Por CONSULTORIO
SELECT
  *
FROM VistaConsultaExterna V  
WHERE
  V.ID_CONSULTORIO=1
;

--LISTAR POR CENTRO MEDICO FECHA
SELECT*
FROM VistaConsultaExterna V
WHERE v.ID_CENTRO_MEDICO=1 AND v.FECHA_HORA= TO_DATE ('27/02/18')
;

--eliminar
DELETE FROM CONSULTAEXTERNA
WHERE ID_CONSULTA = 1;