------------------------- VISTA EFICIO ------------------------
CREATE OR REPLACE VIEW VistaEdificio
AS
SELECT
    C.*,
    M.ID_MEDICO,
    E.ID_EDIFICIO,
    CM.ID_CENTRO_MEDICO,
    CM.NOMBRE,
    CM.ID_TIPO_CENTRO,
    TC.DESCRIPCION,
    M.ID_TURNO
FROM  PISO PI
INNER JOIN EDIFICIO E 
  ON E.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM 
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC 
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO


;

----------------------- CONSULTAS

-- listarTodos /*Por centro*/
SELECT
  *
FROM VistaEdificio
;

--LISTAR POR PISO
SELECT *
  FROM VistaConsultorio V 
  WHERE V.ID_PISO=1
  ;
--LISTAR POR CENTRO MEDICO
SELECT*
FROM VistaEdificio V 
WHERE V.ID_CENTRO_MEDICO=1 OR LIKE V.NOMBRE='HOSPITAL ESCUELA%';

-- listarPor PISO
SELECT *
FROM VistaEdificio V
WHERE V.ID_PISO=1
;

--

--eliminar
--DELETE FROM VistaEdificio
--WHERE ID_EDIFICIO = 1;