----------------------- CONSULTAS

-- listarTodos /*Por centro*/
SELECT
  *
FROM VistaEmergencia
;


--LISTAR POR CENTRO MEDICO
SELECT*
FROM VistaEmergencia V 
WHERE V.ID_CENTRO_MEDICO=1 OR V.centro_medico LIKE 'HOSPITAL ESCUELA%';


-- listarPorPaciente
SELECT
  *
FROM VistaEmergencia V
WHERE
  V.ID_EXPEDIENTE=123
;

-- listarPor MEDICO
SELECT
  *
FROM VistaEmergencia V
WHERE
  V.ID_MEDICO = 1
;

--LISTAR POR HOY
SELECT *
FROM VistaEmergencia V 
WHERE V.FECHA_HORA_ATENCION= SYSDATE;


--LISTAR POR CENTRO MEDICO FECHA
SELECT*
FROM VistaEmergencia V
WHERE v.ID_CENTRO_MEDICO=1 AND v.FECHA_HORA_ATENCION =   TO_DATE ('27/02/18', 'dd/mm/yyyy')
;


--LISTAR POR MEDICO FECHA
SELECT*
FROM VistaEmergencia V
WHERE v.ID_MEDICO=1 AND v.FECHA_HORA_ATENCION=  TO_DATE ('27/02/18', 'dd/mm/yyyy')
;

-- listar Por CLINICA/CONSULTORIO
/*SELECT
  *
FROM VistaEmergencia V  
WHERE
  V.ID_CONSULTORIO=1
;*/


--eliminar
DELETE FROM EMERGENCIA
WHERE ID_INGRESO = 1;