------------------------- VISTA EMERGENCIA ------------------------
CREATE OR REPLACE VIEW VistaEmergencia
AS
SELECT
      E.*,
      MC.TURNO,
      C.*,
      PI.DESCRIPCION,
      PI.EDIFICIO,
      CM.ID_CENTRO_MEDICO,
      CM.NOMBRE,
      EX.ID_EXPEDIENTE,
      EX.ID_PACIENTE,
      PE.P_NOMBRE,
      PE.P_APELLIDO
FROM EMERGENCIA E
INNER JOIN EXPEDIENTE EX 
  ON EX.ID_EXPEDIENTE=E.ID_EXPEDIENTE
INNER JOIN MEDICO M
  ON M.ID_MEDICO= E.ID_MEDICO
INNER JOIN MEDICOCONSULTORIO MC 
  ON MC.ID_MEDICO=M.ID_MEDICO
INNER JOIN CONSULTORIO C 
  ON C.ID_CONSULTORIO=MC.ID_CONSULTORIO
INNER JOIN PISO PI
  ON PI.ID_PISO=C.ID_PISO
INNER JOIN EDIFICIO E 
  ON E.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM 
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC 
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO
INNER JOIN PACIENTE PA 
  ON PA.ID_PACIENTE= EX,ID_PACIENTE
INNER JOIN PERSONA PE 
  ON PE.ID_PERSONA= PA.ID_PERSONA

;

----------------------- CONSULTAS

-- listarTodos /*Por centro*/
SELECT
  *
FROM VistaEmergencia
;


--LISTAR POR CENTRO MEDICO
SELECT*
FROM VistaEmergencia V 
WHERE V.ID_CENTRO_MEDICO=1 OR LIKE V.NOMBRE='HOSPITAL ESCUELA%';


-- listarPorPaciente
SELECT
  *
FROM VistaEmergencia V
WHERE
  V.ID_EXPEDIENTE=123
;

-- listarPor MEDICO
SELECT
  *
FROM VistaEmergencia V
WHERE
  V.ID_MEDICO = 1
;

--LISTAR POR HOY
SELECT *
FROM VistaEmergencia V 
WHERE V.FECHA_HORA= SYSDATE;


--LISTAR POR CENTRO MEDICO FECHA
SELECT*
FROM VistaEmergencia V
WHERE v.ID_CENTRO_MEDICO=1 AND v.FECHA_HORA= TO_DATE ('27/02/18')
;


--LISTAR POR MEDICO FECHA
SELECT*
FROM VistaEmergencia V
WHERE v.ID_MEDICO=1 AND v.FECHA_HORA_ATENCION= TO_DATE ('27/02/18')
;

-- listar Por CLINICA/CONSULTORIO
/*SELECT
  *
FROM VistaEmergencia V  
WHERE
  V.ID_CONSULTORIO=1
;*/


--eliminar
DELETE FROM EMERGENCIA
WHERE ID_INGRESO = 1;