------------------------- VISTA ENFERMEDAD ------------------------
CREATE OR REPLACE VIEW VistaEnfermedad
AS
SELECT
    E.*,
    EC.FECHA_DIAGNOSTICO
    EC.ESTADO,
    CE.*,
    C.ID_CONSULTORIO,
    PI.*,
    CM.ID_CENTRO_MEDICO,
    EX.ID_PACIENTE,
    EX.ID_EXPEDIENTE,
    M.ID_MEDICO,
    CM.NOMBRE,
    CM.TIPOCENTRO,
    TC.DESCRIPCION,
    PE.P_NOMBRE,
    PE.PAPELLIDO
FROM ENFERMEDAD E
INNER JOIN TIPOENFERMEDAD TE
  ON TE.ID_TIPO_ENFERMEDAD= E.ID_TIPO_ENFERMEDAD
INNER JOIN ENFERMEDADCONSULTA EC 
  ON EC.ID_ENFERMEDAD= E.ID_ENFERMEDAD
INNER JOIN CONSULTAEXTERNA CE
  ON CE.ID_CONSULTA= EC.ID_CONSULTA
INNER JOIN CONSULTORIO C
  ON C.ID_CONSULTORIO=CE.ID_CONSULTORIO,
INNER JOIN EXPEDIENTE EX 
  ON EX.ID_EXPEDIENTE=CE.ID_EXPEDIENTE
INNER JOIN MEDICOCONSULTORIO M 
  ON M.ID_MEDICO=CE.ID_MEDICO
INNER JOIN PISO PI
  ON PI.ID_PISO=C.ID_PISO
INNER JOIN EDIFICIO E 
  ON E.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM 
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC 
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO
INNER JOIN PACIENTE PA 
  ON PA.ID_PACIENTE= EX,ID_PACIENTE
INNER JOIN PERSONA PE 
  ON PE.ID_PERSONA= PA.ID_PERSONA

;

----------------------- CONSULTAS

-- listarTodos /*Por centro*/
SELECT
  *
FROM VistaEnfermedad
;
--LISTA TIPO ENFERMEDAD
SELECT *
FROM VistaEnfermedad V 
WHERE V.ID_TIPO_ENFERMEDAD=1

-- listarPorPaciente
SELECT
  *
FROM VistaEnfermedad V
WHERE
  V.ID_EXPEDIENTE=123
;


--eliminar
DELETE FROM ENFERMEDAD
WHERE ID_ENFERMEDAD = 1;