------------------------- VISTA Examen ------------------------
CREATE OR REPLACE VIEW VistaExamen
AS
SELECT
    E.*,
    TE.DESCRIPCION,
    PI.*,
    CM.ID_CENTRO_MEDICO,
    EX.ID_PACIENTE,
    EX.ID_EXPEDIENTE,
    CM.NOMBRE,
    CM.TIPOCENTRO,
    TC.DESCRIPCION,
    PE.P_NOMBRE,
    PE.PAPELLIDO
FROM EXAMEN E 
INNER JOIN TIPOEXAMEN TE 
  ON TE.ID_TIPO= E.ID_TIPO
INNER JOIN EXPEDIENTE EX 
  ON EX.ID_EXPEDIENTE=CE.ID_EXPEDIENTE
INNER JOIN PISO PI
  ON PI.ID_PISO=C.ID_PISO
INNER JOIN EDIFICIO E 
  ON E.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM 
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC 
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO
INNER JOIN PACIENTE PA 
  ON PA.ID_PACIENTE= EX,ID_PACIENTE
INNER JOIN PERSONA PE 
  ON PE.ID_PERSONA= PA.ID_PERSONA

;

----------------------- CONSULTAS

-- listarTodos /*Por centro*/
SELECT
  *
FROM VistaExamen
;
--LISTA TIPO EXAMEN
SELECT *
FROM VistaExamen V 
WHERE V.ID_TIPO=1

--LISTAR POR CENTRO
SELECT *
FROM VistaExamen V 
WHERE V.ID_CENTRO_MEDICO=1 OR LIKE V.NOMBRE='%HOSPITAL ESCUELA';

-- listarPorPaciente
SELECT
  *
FROM VistaExamen V
WHERE
  V.ID_EXPEDIENTE=123
;


--eliminar
DELETE FROM EXAMEN
WHERE ID_EXAMEN = 1;