--listarPorCentro
SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE v.ID_CENTRO_MEDICO = 1;

--listarPorPaciente
SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE v.ID_EXPEDIENTE =1;

-- listarPorMedico
SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE
  v.ID_CENTRO_MEDICO = 1
  AND v.ID_MEDICO = 1
;

-- listarPorPiso

SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE v.ID_PISO = 1;

-- listarPorFecha
SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE
  EXTRACT(DAY FROM v.FECHA_HORA_INGRESO) = EXTRACT(DAY FROM TO_DATE('12/02/2011', 'dd/mm/yyyy'))
  AND EXTRACT(MONTH FROM v.FECHA_HORA_INGRESO) = EXTRACT(MONTH FROM TO_DATE('12/02/2011', 'dd/mm/yyyy'))
  AND EXTRACT(YEAR FROM v.FECHA_HORA_INGRESO) = EXTRACT(YEAR FROM TO_DATE('12/02/2011', 'dd/mm/yyyy'))
  AND v.ID_CENTRO_MEDICO = 4
;


-- eliminar
DELETE FROM HOSPITALIZACION
WHERE ID_INGRESO = 1;
