-- listarTodos /*Por Centro*/
SELECT DISTINCT
  e.ID_CENTRO_MEDICO,
  v.*
FROM VISTAMEDICO v
INNER JOIN MEDICOCONSULTORIO mc
  ON mc.ID_MEDICO = v.ID_MEDICO
INNER JOIN CONSULTORIO c
  ON c.ID_CONSULTORIO = mc.ID_CONSULTORIO
INNER JOIN PISO p
  ON p.ID_PISO = c.ID_PISO
INNER JOIN EDIFICIO e
  ON e.ID_EDIFICIO = p.ID_PISO
WHERE
  e.ID_CENTRO_MEDICO = 1
ORDER BY v.ESPECIALIDAD
;

-- listar
SELECT
  *
FROM VISTAMEDICO v
WHERE v.ID_MEDICO = 1;

--buscarPorNombre
SELECT
  *
FROM VISTAMEDICO v
WHERE
  v.P_NOMBRE = 'Jose'
  OR v.S_NOMBRE = 'David'
;

--buscarPorApellido
SELECT
  *
FROM VISTAMEDICO v
WHERE
  v.P_APELLIDO = 'Alderson'
  OR v.S_APELLIDO = 'Rodriguez'
;

--buscarPorNoIdentidad
SELECT
  *
FROM VISTAMEDICO v
WHERE
  v.NO_IDENTIDAD = '125'
;

-- LISTAR ESPECIALIDADES MEDICAS
SELECT
  *
FROM ESPECIALIDAD;