-------------------------- VISTA --------------------------
CREATE VIEW VIstaTratamiento
AS
SELECT
t.*
,tp.TIPO_TRATAMIENTO
,v.VIA_SUMINISTRO
FROM TRATAMIENTO t
INNER JOIN TIPOTRATAMIENTO tp
ON t.ID_TIPO = tp.ID_TIPO
INNER JOIN VIASUMINISTRO v
ON t.ID_VIA_SUMINISTRO = v.ID_VIA_SUMINISTRO
;

-- agregarTipoTratamiento
INSERT INTO TIPOTRATAMIENTO
(TIPO_TRATAMIENTO) VALUES
('Lorem');

-- listarTipoTratamiento
SELECT
  *
FROM TIPOTRATAMIENTO;

-- agregarViaSuministro
INSERT INTO VIASUMINISTRO
(VIA_SUMINISTRO) VALUES
('Lorem ipsum');

-- listarViaSuministro
SELECT
  *
FROM VIASUMINISTRO;


-- listarTodos
SELECT
  *
FROM VIstaTratamiento;

-- listarPorPaciente
SELECT
e.ID_PACIENTE
,c.ID_CONSULTA
,v.*
FROM TRATAMIENTOCONSULTA tc
INNER JOIN CONSULTAEXTERNA c
  ON tc.ID_CONSULTA = c.ID_CONSULTA
INNER JOIN EXPEDIENTE e
  ON c.ID_EXPEDIENTE = e.ID_EXPEDIENTE
INNER JOIN VIstaTratamiento v
  ON v.ID_TRATAMIENTO = tc.ID_TRATAMIENTO
WHERE e.ID_PACIENTE = 1;