-- agregarTipoTratamiento
INSERT INTO TIPOTRATAMIENTO
(TIPO_TRATAMIENTO) VALUES
('Lorem');

-- listarTipoTratamiento
SELECT
  *
FROM TIPOTRATAMIENTO;

-- agregarViaSuministro
INSERT INTO VIASUMINISTRO
(VIA_SUMINISTRO) VALUES
('Lorem ipsum');

-- listarViaSuministro
SELECT
  *
FROM VIASUMINISTRO;


-- listarTodos
SELECT
  *
FROM VIstaTratamiento;

-- listarPorPaciente
SELECT
e.ID_PACIENTE
,c.ID_CONSULTA
,v.*
FROM TRATAMIENTOCONSULTA tc
INNER JOIN CONSULTAEXTERNA c
  ON tc.ID_CONSULTA = c.ID_CONSULTA
INNER JOIN EXPEDIENTE e
  ON c.ID_EXPEDIENTE = e.ID_EXPEDIENTE
INNER JOIN VIstaTratamiento v
  ON v.ID_TRATAMIENTO = tc.ID_TRATAMIENTO
WHERE e.ID_PACIENTE = 1;