--listarPorCentro
SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE v.ID_CENTRO_MEDICO =%s;

--listarPorPaciente
SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE v.ID_EXPEDIENTE =%s;

-- listarPorMedico
SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE
  v.ID_CENTRO_MEDICO =%s
  AND v.ID_MEDICO =%s
;

-- listarPorPiso

SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE v.ID_PISO =%s;

-- listarPorFecha
SELECT
  *
FROM VISTAHOSPITALIZACIONES v
WHERE
  EXTRACT(DAY FROM v.FECHA_HORA_INGRESO) = EXTRACT(DAY FROM TO_DATE('12/02/2011', 'dd/mm/yyyy'))
  AND EXTRACT(MONTH FROM v.FECHA_HORA_INGRESO) = EXTRACT(MONTH FROM TO_DATE('12/02/2011', 'dd/mm/yyyy'))
  AND EXTRACT(YEAR FROM v.FECHA_HORA_INGRESO) = EXTRACT(YEAR FROM TO_DATE('12/02/2011', 'dd/mm/yyyy'))
  AND v.ID_CENTRO_MEDICO =%s
;


-- eliminar
DELETE FROM HOSPITALIZACION
WHERE ID_INGRESO =%s;
