-- listarTodos /*Por Centro*/
SELECT DISTINCT
  e.ID_CENTRO_MEDICO,
  v.*
FROM VISTAMEDICO v
INNER JOIN MEDICOCONSULTORIO mc
  ON mc.ID_MEDICO = v.ID_MEDICO
INNER JOIN CONSULTORIO c
  ON c.ID_CONSULTORIO = mc.ID_CONSULTORIO
INNER JOIN PISO p
  ON p.ID_PISO = c.ID_PISO
INNER JOIN EDIFICIO e
  ON e.ID_EDIFICIO = p.ID_PISO
WHERE
  e.ID_CENTRO_MEDICO =%s
ORDER BY v.ESPECIALIDAD
;

-- listar
SELECT
  *
FROM VISTAMEDICO v
WHERE v.ID_MEDICO =%s;

--buscarPorNombre
SELECT
  *
FROM VISTAMEDICO v
WHERE
  v.P_NOMBRE = '%s'
  OR v.S_NOMBRE = '%s'
;

--buscarPorApellido
SELECT
  *
FROM VISTAMEDICO v
WHERE
  v.P_APELLIDO = '%s'
  OR v.S_APELLIDO = '%s'
;

--buscarPorNoIdentidad
SELECT
  *
FROM VISTAMEDICO v
WHERE
  v.NO_IDENTIDAD = '%s'
;