/*** Vista 10: *****/
 /*** Tratamiento por Consulta *****/
CREATE OR REPLACE VIEW  VistaTratamientoConsultas
AS
SELECT
  vc.*,
  t.ID_TRATAMIENTO,
  t.DOSIS,
  t.INTERVALO_TIEMPO,
  t.FECHA_INICIO,
  t.DURACION_TRATAMIENTO as DURACION,
  tt.TIPO_TRATAMIENTO,
  vs.VIA_SUMINISTRO
FROM TRATAMIENTOCONSULTA tc
INNER JOIN VistaConsultas vc
  ON vc.ID_CONSULTA = tc.ID_CONSULTA
INNER JOIN TRATAMIENTO t
  ON tc.ID_TRATAMIENTO = t.ID_TRATAMIENTO
INNER JOIN TIPOTRATAMIENTO tt
  ON tt.ID_TIPO = t.ID_TIPO
INNER JOIN VIASUMINISTRO vs
  ON vs.ID_VIA_SUMINISTRO = t.ID_VIA_SUMINISTRO
;