/*** ------------------- VISTA AMBULANCIA ------------------------ *****/
CREATE OR REPLACE VIEW vistaAmbulancia
AS
SELECT 
 A.*, CM.NOMBRE, APH.ID_ATENCION,p.*
FROM AMBULANCIA A 
INNER JOIN CENTROMEDICO CM
  ON CM.ID_CENTRO_MEDICO=A.ID_CENTRO_MEDICO
INNER JOIN  ATENCIONPREHOSPITALARIA APH
  ON APH.ID_AMBULANCIA= A.ID_AMBULANCIA
INNER JOIN PARAMEDICO P
  ON P.ID_PARAMEDICO=APH.ID_PARAMEDICO;