/*** ------------------- VISTAS ATENCION PRE HOSPITALARIA ------------------------ *****/
CREATE OR REPLACE VIEW vistaAPH
AS
SELECT
  APH.ID_ATENCION,
  A.PLACA,
  CM.NOMBRE,
  CM.ID_CENTRO_MEDICO,
  APH.OBSERVACION,
  Ex.ID_EXPEDIENTE,
  P.P_NOMBRE,
  P.S_NOMBRE,
  P.P_APELLIDO,
  P.S_APELLIDO,
  p.NO_IDENTIDAD,
  P.SEXO,
  PA.ID_PARAMEDICO,
  APH.FECHA_HORA_ATENCION
FROM AMBULANCIA A 
INNER JOIN CENTROMEDICO CM
  ON CM.ID_CENTRO_MEDICO=A.ID_CENTRO_MEDICO
INNER JOIN  ATENCIONPREHOSPITALARIA APH
  ON APH.ID_AMBULANCIA= A.ID_AMBULANCIA
INNER JOIN PARAMEDICO PA
  ON PA.ID_PARAMEDICO=APH.ID_PARAMEDICO
  INNER JOIN EXPEDIENTE EX
  ON EX.ID_EXPEDIENTE=APH.ID_EXPEDIENTE
INNER JOIN PACIENTE PAC
  ON PAC.ID_PACIENTE=EX.ID_PACIENTE
INNER JOIN PERSONA P
  ON P.ID_PERSONA= PA.ID_PARAMEDICO
;