/*** ------------------- VISTA CIRUGIA ------------------------ *****/
CREATE OR REPLACE VIEW VistaCirugia
AS
SELECT
    C.ID_INGRESO,
    C.ID_MEDICO,
    C.FECHA_HORA,
    TC.ID_TIPO_CIRUGIA,
    TC.DESCRIPCION as tipo_cirugia,
    H.FECHA_HORA_ALTA,
    H.FECHA_HORA_INGRESO,
    PI.ID_PISO,
    PI.DESCRIPCION as SALA,
    PI.ID_EDIFICIO,
    PI.DESCRIPCION AS descripcion_piso,
    CM.ID_CENTRO_MEDICO,
    cm.NOMBRE as centro_medico,
    CM.ID_TIPO_CENTRO,
    PE.P_NOMBRE,
    PE.S_NOMBRE,
    PE.P_APELLIDO,
    PE.S_APELLIDO,
    PE.NO_IDENTIDAD,
    PE.SEXO,
    ex.ID_EXPEDIENTE,
    vm.p_nombre || ' '  || vm.s_nombre ||  ' '  || vm.p_apellido || ' '  || vm.s_apellido as medico
FROM CIRUGIA C
INNER JOIN  TIPOCIRUGIA TC
  ON TC.ID_TIPO_CIRUGIA= C.ID_TIPO_CIRUGIA
INNER JOIN HOSPITALIZACION H
  ON H.ID_INGRESO= C.ID_INGRESO
INNER JOIN PISO PI
  ON PI.ID_PISO=H.ID_PISO
INNER JOIN EDIFICIO E
  ON E.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN EXPEDIENTE EX
  ON EX.ID_EXPEDIENTE=H.ID_EXPEDIENTE
INNER JOIN PACIENTE PA
  ON PA.ID_PACIENTE= EX.ID_PACIENTE
INNER JOIN PERSONA PE
  ON PE.ID_PERSONA= PA.ID_PERSONA
INNER JOIN VISTAMEDICO vm
  ON vm.ID_MEDICO = c.ID_MEDICO
;