
/*** ------------------- VISTA CONSULTA EXTERNA ------------------------ *****/
CREATE OR REPLACE VIEW VistaConsultaExterna
AS
SELECT
  CE.ID_CONSULTA,
  CE.FECHA_HORA,
  C.ID_CONSULTORIO,
  PI.ID_PISO,
  PI.DESCRIPCION as piso,
  CM.ID_CENTRO_MEDICO,
  EX.ID_PACIENTE,
  EX.ID_EXPEDIENTE,
  M.ID_MEDICO,
  CM.NOMBRE as centro_medico,
  CM.ID_TIPO_CENTRO,
  TC.DESCRIPCION AS TIPO_CENTRO,
  PE.P_NOMBRE,
  PE.S_NOMBRE,
  PE.P_APELLIDO,
  PE.S_APELLIDO,
  PE.NO_IDENTIDAD,
  PE.SEXO
FROM CONSULTAEXTERNA CE
INNER JOIN CONSULTORIO C
  ON C.ID_CONSULTORIO=CE.ID_CONSULTORIO
INNER JOIN EXPEDIENTE EX
  ON EX.ID_EXPEDIENTE=CE.ID_EXPEDIENTE
INNER JOIN MEDICOCONSULTORIO M
  ON M.ID_MEDICO=CE.ID_MEDICO
INNER JOIN PISO PI
  ON PI.ID_PISO=C.ID_PISO
INNER JOIN EDIFICIO E
  ON E.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO
INNER JOIN PACIENTE PA
  ON PA.ID_PACIENTE= EX.ID_PACIENTE
INNER JOIN PERSONA PE
  ON PE.ID_PERSONA= PA.ID_PERSONA
;