CREATE OR REPLACE VIEW VistaEdificio
AS
SELECT
    CM.ID_CENTRO_MEDICO,
    CM.NOMBRE,
    CM.ID_TIPO_CENTRO,
    TC.DESCRIPCION AS TIPO_CENTRO
  ,e.ID_EDIFICIO
  ,e.NOMBRE as edificio
FROM  EDIFICIO E
INNER JOIN CENTROMEDICO CM
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO
;