/*** ------------------- VISTA EFICIO ------------------------ *****/
CREATE OR REPLACE VIEW VistaEdificioPiso
AS
SELECT
    PI.*,
    CM.ID_CENTRO_MEDICO,
    CM.NOMBRE,
    CM.ID_TIPO_CENTRO,
    TC.DESCRIPCION AS TIPO_CENTRO
FROM  PISO PI
INNER JOIN EDIFICIO E 
  ON E.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM 
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC 
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO
;