CREATE OR REPLACE VIEW VistaPiso
AS
SELECT
p.ID_PISO
,p.DESCRIPCION as piso
,e.ID_EDIFICIO
,e.NOMBRE as edificio
FROM PISO p
INNER JOIN EDIFICIO e
  ON p.ID_EDIFICIO = e.ID_EDIFICIO
INNER JOIN CENTROMEDICO c
  ON e.ID_CENTRO_MEDICO = c.ID_CENTRO_MEDICO
;