/*** ------------------- VISTA Examen ------------------------ *****/
CREATE OR REPLACE VIEW VistaExamen
AS
SELECT
  E.ID_EXAMEN,
  E.URL_DOCUMENTO,
  E.FECHA,
  TE.ID_TIPO,
  TE.DESCRIPCION AS TIPO_EXAMEN,
  EX.ID_EXPEDIENTE,
  PA.ID_PACIENTE,
  PE.P_NOMBRE,
  PE.S_NOMBRE,
  PE.P_APELLIDO,
  PE.S_APELLIDO,
  PE.NO_IDENTIDAD,
  PE.SEXO,
  CM.ID_CENTRO_MEDICO,
  cm.NOMBRE as centro_medico
FROM EXAMEN E
INNER JOIN TIPOEXAMEN TE
  ON TE.ID_TIPO= E.ID_TIPO
INNER JOIN EXPEDIENTE EX
  ON EX.ID_EXPEDIENTE=E.ID_EXPEDIENTE
INNER JOIN PACIENTE PA
  ON PA.ID_PACIENTE= EX.ID_PACIENTE
INNER JOIN PERSONA PE
  ON PE.ID_PERSONA= PA.ID_PERSONA
INNER JOIN CENTROMEDICO CM
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO
;