/*** ------------------- VISTA ENFERMEDAD PACIENTE ------------------------ *****/
CREATE OR REPLACE VIEW VistaEnfermedadPaciente
AS
SELECT
    E.ID_ENFERMEDAD,
    E.ID_TIPO_ENFERMEDAD,
    E.ENFERMEDAD,
    EC.FECHA_DIAGNOSTICO,
    EC.ESTADO,
    CE.ID_CONSULTA,
    CE.FECHA_HORA,
    C.ID_CONSULTORIO,
    PI.*,
    EX.ID_PACIENTE,
    EX.ID_EXPEDIENTE,
    M.ID_MEDICO,
    CM.NOMBRE,
    CM.ID_CENTRO_MEDICO,
    CM.ID_TIPO_CENTRO,
    TC.DESCRIPCION AS TIPO_CENTRO,
    PE.P_NOMBRE,
    PE.P_APELLIDO
FROM ENFERMEDAD E
INNER JOIN TIPOENFERMEDAD TE
  ON TE.ID_TIPO_ENFERMEDAD= E.ID_TIPO_ENFERMEDAD
INNER JOIN ENFERMEDADCONSULTA EC 
  ON EC.ID_ENFERMEDAD= E.ID_ENFERMEDAD
INNER JOIN CONSULTAEXTERNA CE
  ON CE.ID_CONSULTA= EC.ID_CONSULTA
INNER JOIN CONSULTORIO C
  ON C.ID_CONSULTORIO=CE.ID_CONSULTORIO
INNER JOIN EXPEDIENTE EX 
  ON EX.ID_EXPEDIENTE=CE.ID_EXPEDIENTE
INNER JOIN MEDICO M
  ON M.ID_MEDICO=CE.ID_MEDICO
INNER JOIN PISO PI
  ON PI.ID_PISO=C.ID_PISO
INNER JOIN EDIFICIO E 
  ON E.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM 
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC 
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO
INNER JOIN PACIENTE PA 
  ON PA.ID_PACIENTE= EX.ID_PACIENTE
INNER JOIN PERSONA PE
  ON PE.ID_PERSONA= PA.ID_PERSONA
;
