/*** -------------------- VISTATRATAMIENTO -------------------------- *****/
CREATE OR REPLACE VIEW VistaTratamiento
AS
SELECT
t.*
,tp.TIPO_TRATAMIENTO
,v.VIA_SUMINISTRO
FROM TRATAMIENTO t
INNER JOIN TIPOTRATAMIENTO tp
ON t.ID_TIPO = tp.ID_TIPO
INNER JOIN VIASUMINISTRO v
ON t.ID_VIA_SUMINISTRO = v.ID_VIA_SUMINISTRO
;