
/*** ------------------------- VISTA ------------------------------- *****/

CREATE OR REPLACE VIEW VistaTelefonoPersona
AS
SELECT
  p.id_persona
  ,t.ID_TELEFONO
  ,tipo.TIPO_TELEFONO
  ,pa.CODIGO_POSTAL as codigo_area
  ,t.TELEFONO
FROM TELEFONOPERSONA tp
INNER JOIN TELEFONO t
  ON tp.ID_TELEFONO = t.ID_TELEFONO
INNER JOIN PERSONA p
  ON tp.ID_PERSONA = p.ID_PERSONA
INNER JOIN TIPOTELEFONO tipo
  On t.ID_TIPO_TELEFONO = tipo.ID_TIPO_TELEFONO
INNER JOIN pais pa
  ON pa.ID_PAIS = t.ID_PAIS
ORDER BY id_persona
;

CREATE OR REPLACE VIEW VistaTelefonoCentroMedico
AS
SELECT
  c.ID_CENTRO_MEDICO
  ,t.ID_TELEFONO
  ,tipo.TIPO_TELEFONO
  ,pa.CODIGO_POSTAL as codigo_area
  ,t.TELEFONO
FROM TELEFONOCENTROMEDICO tc
INNER JOIN TELEFONO t
  ON tc.ID_TELEFONO = t.ID_TELEFONO
INNER JOIN CENTROMEDICO c
  ON tc.ID_CENTRO_MEDICO = c.ID_CENTRO_MEDICO
INNER JOIN TIPOTELEFONO tipo
  On t.ID_TIPO_TELEFONO = tipo.ID_TIPO_TELEFONO
INNER JOIN pais pa
  ON pa.ID_PAIS = t.ID_PAIS
ORDER BY ID_CENTRO_MEDICO
;
