------------------------- VISTA EMERGENCIA ------------------------
CREATE OR REPLACE VIEW VistaEmergencia
AS
SELECT
  E.*,
  MC.ID_TURNO,
  C.ID_CONSULTORIO,
  PI.DESCRIPCION AS piso,
  PI.ID_EDIFICIO,
  (SELECT P_NOMBRE ||' '|| S_NOMBRE  ||' '||  P_APELLIDO||' '|| S_APELLIDO FROM VISTAMEDICO v WHERE v.ID_MEDICO = m.ID_MEDICO) as medico,
  (SELECT ESPECIALIDAD FROM VISTAMEDICO v WHERE v.ID_MEDICO = m.ID_MEDICO) as especialidad,
  CM.NOMBRE as centro_medico,
  EX.ID_PACIENTE,
  PE.P_NOMBRE,
  PE.P_APELLIDO
FROM EMERGENCIA E
INNER JOIN EXPEDIENTE EX 
  ON EX.ID_EXPEDIENTE=E.ID_EXPEDIENTE
INNER JOIN MEDICO M
  ON M.ID_MEDICO= E.ID_MEDICO
INNER JOIN MEDICOCONSULTORIO MC 
  ON MC.ID_MEDICO=M.ID_MEDICO
INNER JOIN CONSULTORIO C 
  ON C.ID_CONSULTORIO=MC.ID_CONSULTORIO
INNER JOIN PISO PI
  ON PI.ID_PISO=C.ID_PISO
INNER JOIN EDIFICIO Ed
  ON Ed.ID_EDIFICIO=PI.ID_EDIFICIO
INNER JOIN CENTROMEDICO CM 
  ON CM.ID_CENTRO_MEDICO= E.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TC 
  ON TC.ID_TIPO_CENTRO= CM.ID_TIPO_CENTRO
INNER JOIN PACIENTE PA 
  ON PA.ID_PACIENTE= EX.ID_PACIENTE
INNER JOIN PERSONA PE 
  ON PE.ID_PERSONA= PA.ID_PERSONA
;
