CREATE OR REPLACE VIEW VistaUsuario AS
SELECT
  p.ID_PERSONA
  ,p.P_NOMBRE
  ,p.S_NOMBRE
  ,p.P_APELLIDO
  ,p.S_APELLIDO
  ,p.DIRECCION
  ,p.NO_IDENTIDAD
  ,p.ID_PAIS
  ,pa.NOMBRE as pais
  ,p.CORREO
  ,u.ID_USUARIO
  ,u.ID_TIPO_USUARIO
  ,tu.TIPO as tipo_usuario
  ,cm.ID_CENTRO_MEDICO
  ,cm.NOMBRE as centro_medico
  ,tp.ID_TIPO_CENTRO
  , tp.DESCRIPCION as tipo_centro
  , tp.HORARIO
FROM PERSONA P
INNER JOIN USUARIO U
  ON P.ID_PERSONA=U.ID_PERSONA
INNER JOIN CENTROMEDICO CM
  ON CM.ID_CENTRO_MEDICO=U.ID_CENTRO_MEDICO
INNER JOIN TIPOCENTRO TP
  ON CM.ID_TIPO_CENTRO = TP.ID_TIPO_CENTRO
INNER JOIN TIPOUSUARIO TU
  ON U.ID_TIPO_USUARIO = TU.ID_TIPO_USUARIO
INNER JOIN PAIS pa
  ON P.ID_PAIS = pa.ID_PAIS